
secrets:
  token:
    description: 'GitHub token'
    required: false
outputs:
  remaining:
    description: 'The remaining rate limit after running the action'
    value: ${{ jobs.calc_rate_limit.outputs.remaining }}
runs:
  using: 'composite'
  steps:
    - name: Install jq
      run: |
        if ! command -v jq &> /dev/null
        then
          sudo apt install -y jq
        fi
      shell: bash

    - name: Calculate rate Limit
      id: calc_rate_limit
      run: |
        chmod +x ratelimit.sh
        ./ratelimit.sh "${{ secrets.token }}"
      shell: bash

    - name: Print remaining rate limit
      run: |
        echo "Remaining rate limit: ${{ steps.calc_rate_limit.outputs.remaining }}"
  outputs:
    remaining: ${{ steps.calc_rate_limit.outputs.remaining }}
