inputs:
  token:
    description: 'GitHub token'
    required: false
outputs:
  remaining:
    description: 'The remaining rate limit after running the action'
    value: ${{ steps.calc_rate_limit.outputs.remaining }}
runs:
  using: 'composite'
  steps:
    - name: Get PR for commit
      id: get-pr
      uses: actions/github-script@v5
      with:
        script: |
          const { owner, repo } = context.repo
          const { sha } = context.sha
          const { data: pullRequests } = await github.rest.pulls.list({
            owner,
            repo,
            state: 'open',
          })
          const pullRequest = pullRequests.find(pr => pr.head.sha === sha)
          return pullRequest ? pullRequest.number : null
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install jq
      run: |
        if ! command -v jq &> /dev/null
        then
          sudo apt install -y jq
        fi
      shell: bash

    - name: Calculate rate Limit
      id: calc_rate_limit
      run: |
        chmod +x ratelimit.sh
        ./ratelimit.sh "${{ inputs.token }}"
      shell: bash

    - name: Print remaining rate limit
      run: |
        echo "Remaining rate limit: ${{ steps.calc_rate_limit.outputs.remaining }} :rocket:" >> $GITHUB_STEP_SUMMARY
      shell: bash
