name: 'check GitHub rate limit'
description: 'displays GitHub rate limit'
inputs:
  token:
    description: 'GitHub token'
    required: false
outputs:
  remaining:
    description: 'The remaining rate limit after running the action'
    value: ${{ steps.check_rate_limit.outputs.remaining }}  # Set the output here
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install jq
      run: |
        if ! command -v jq &> /dev/null
        then
          sudo apt install -y jq
        fi
      shell: bash

    - name: Check Rate Limit
      id: check_rate_limit  # Add an id to this step
      run: |
        chmod +x ratelimit.sh
        ./ratelimit.sh "${{ inputs.token }}"
        echo "remaining=$(cat $GITHUB_OUTPUT)" >> $GITHUB_ENV  # Set the output as an environment variable
      shell: bash
