name: 'check GitHub rate limit'
description: 'displays GitHub rate limit'
inputs:
  token:
    description: 'GitHub token'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install jq
      run: |
        if ! command -v jq &> /dev/null
        then
          sudo apt install -y jq
        fi
      shell: bash

    - name: Check Rate Limit
      run: |
        chmod +x ratelimit.sh
        ./ratelimit.sh "${{ inputs.token }}"
      shell: bash
