on:
  workflow_call:
    secrets:
      token:
        description: 'GitHub token'
        required: false
    outputs:
      remaining:
        description: 'The remaining rate limit after running the action'
        value: ${{ jobs.calc.outputs.remaining }}
jobs:
  calc:
    runs-on: ubuntu-latest
    steps:
      uses: wakamex/rate-limit-action@main
      with:
        action: calc
    secrets:
      token: ${{ secrets.GH_GITHUB_COM_TOKEN }}
  show:
    runs-on: ubuntu-latest
    needs: calc
    steps:
      uses: wakamex/rate-limit-action@main
      with:
        action: show
        remaining: ${{ needs.calc.outputs.remaining }}
