inputs:
  remaining:
    description: 'The remaining rate limit'
    required: true
    type: string
runs:
  steps:
    - name: "Print remaining rate limit"
      run: |
        echo "Remaining rate limit: ${{ inputs.remaining }}"
      shell: bash
