inputs:
  remaining:
    description: 'The remaining rate limit'
    required: true
    type: string
runs:
  steps:
    - name: "Limit: ${{ inputs.remaining }}"
      run: echo "Remaining rate limit: ${{ inputs.remaining }}"
      shell: bash
