name: Call reusable workflow

on:
  workflow_dispatch:
  push:

jobs:
  call_reusable_workflow:
    uses: your-repo/.github/workflows/your-reusable-workflow.yml@branch
    with:
      token: ${{ secrets.GH_GITHUB_COM_TOKEN }}
