name: Call reusable workflow

on:
  workflow_dispatch:
  push:

jobs:
  limit:
    uses: wakamex/rate-limit-action/.github/workflows/reusable.yml@master
    secrets:
      token: ${{ secrets.GH_GITHUB_COM_TOKEN }}
  show:
    needs: limit
    uses: wakamex/rate-limit-action/.github/workflows/show-rate-limit.yml@master
    with:
      remaining: ${{ needs.limit.outputs.remaining }}
