on:
  push:
    branches:
      - main

jobs:
  _:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Caller Action
        uses: wakamex/rate-limit-action@main
        with:
          action: aggregate
          token: ${{ secrets.GH_GITHUB_COM_TOKEN }}
