on:
  workflow_dispatch:
  push:

jobs:
  calc:
    uses: wakamex/rate-limit-action@main
    with:
      action: calc
    secrets:
      token: ${{ secrets.GH_GITHUB_COM_TOKEN }}
  show:
    needs: calc
    uses: wakamex/rate-limit-action@main
    with:
      action: show
      remaining: ${{ needs.calc.outputs.remaining }}
