on:
  push:

jobs:
  _:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Wrapper
        uses: wakamex/rate-limit-action@main
        with:
          action: wrapper
          token: ${{ secrets.GH_GITHUB_COM_TOKEN }}
