name: Check Rate Limit

on:
  workflow_run:
    workflows: ["Lint"]
    types:
      - completed

jobs:
  Rate:
    runs-on: ubuntu-latest
    steps:
      - id: calc
        uses: wakamex/rate-limit-action/calc@master
        with:
          token: ${{ secrets.GH_GITHUB_COM_TOKEN }}
    outputs:
      remaining: ${{ steps.calc.outputs.remaining }}
