name: 'check GitHub rate limit'
on:
  workflow_call:
    inputs:
      token:
        description: 'GitHub token'
        required: false
        type: string
    outputs:
      remaining:
        description: 'The remaining rate limit after running the action'
        value: ${{ jobs.check_rate_limit.outputs.remaining }}
    secrets:
      GH_GITHUB_COM_TOKEN:
        required: false

run-name: "Rate limit check: ${{ jobs.check_rate_limit.outputs.remaining }}"
jobs:
  check_rate_limit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install jq
        run: |
          if ! command -v jq &> /dev/null
          then
            sudo apt install -y jq
          fi
        shell: bash

      - name: Check Rate Limit
        id: check_rate_limit
        run: |
          chmod +x ratelimit.sh
          ./ratelimit.sh "${{ inputs.token }}"
          echo "remaining=$(cat $GITHUB_OUTPUT)" >> $GITHUB_ENV
        shell: bash
    outputs:
      remaining: ${{ steps.check_rate_limit.outputs.remaining }}
