name: 'check GitHub rate limit'
on:
  workflow_call:
    secrets:
      token:
        description: 'GitHub token'
        required: false
jobs:
  check_rate_limit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install jq
        run: |
          if ! command -v jq &> /dev/null
          then
            sudo apt install -y jq
          fi
        shell: bash

      - name: Check Rate Limit
        id: check_rate_limit
        run: |
          chmod +x ratelimit.sh
          ./ratelimit.sh "${{ secrets.token }}"
        shell: bash

      - name: Print remaining rate limit
        run: |
          echo "Remaining rate limit: ${{ steps.check_rate_limit.outputs.remaining }}"
    outputs:
      remaining: ${{ steps.check_rate_limit.outputs.remaining }}
