name: 'check GitHub rate limit'
on:
  workflow_call:
    inputs:
      token:
        description: 'GitHub token'
        required: true
        type: string
jobs:
  check_rate_limit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install jq
        run: |
          if ! command -v jq &> /dev/null
          then
            sudo apt install -y jq
          fi
        shell: bash

      - name: Check Rate Limit
        id: check_rate_limit
        run: |
          chmod +x ratelimit.sh
          ./ratelimit.sh "${{ inputs.token }}"
        shell: bash
    outputs:
      remaining: ${{ steps.check_rate_limit.outputs.remaining }}
