run-name: "Limit: ${{ jobs.show.outputs.remaining }}"
on:
  workflow_run:
    workflows: ["Check Rate Limit"]
    types:
      - completed
jobs:
  show:
    runs-on: ubuntu-latest
    steps:
      - name: Get output from Rate workflow
        id: rate
        uses: actions/github-script@v5
        with:
          script: |
            const runId = ${{ github.event.workflow_run.id }}
            const outputName = 'remaining'
            const octokit = github.getOctokit(github.token)
            const { data: { outputs } } = await octokit.request('GET /repos/{owner}/{repo}/actions/runs/{run_id}', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: runId
            })
            return outputs[outputName].value
      - name: Print remaining rate limit
        run: |
          echo "Remaining rate limit: ${{ steps.rate.outputs.result }}"
    outputs:
      remaining: ${{ steps.rate.outputs.result }}